# Generated by Django 3.2.22 on 2024-06-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240608_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('crvena', 'Crvena'), ('plava', 'Plava'), ('zelena', 'Zelena'), ('crna', 'Crna'), ('bijela', 'Bijela'), ('srebrna', 'Srebrna'), ('žuta', 'Žuta'), ('narančasta', 'Narančasta'), ('ljubičasta', 'Ljubičasta'), ('smeđa', 'Smeđa')], max_length=20),
        ),
    ]
